set(_CATKIN_CURRENT_PACKAGE "mindbot_msgs")
set(mindbot_msgs_VERSION "0.0.0")
set(mindbot_msgs_MAINTAINER "lavit <lavit@todo.todo>")
set(mindbot_msgs_PACKAGE_FORMAT "2")
set(mindbot_msgs_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "geometry_msgs" "sensor_msgs")
set(mindbot_msgs_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "geometry_msgs" "sensor_msgs")
set(mindbot_msgs_BUILDTOOL_DEPENDS "catkin")
set(mindbot_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(mindbot_msgs_EXEC_DEPENDS "roscpp" "rospy" "geometry_msgs" "sensor_msgs" "message_runtime")
set(mindbot_msgs_RUN_DEPENDS "roscpp" "rospy" "geometry_msgs" "sensor_msgs" "message_runtime")
set(mindbot_msgs_TEST_DEPENDS )
set(mindbot_msgs_DOC_DEPENDS )
set(mindbot_msgs_URL_WEBSITE "")
set(mindbot_msgs_URL_BUGTRACKER "")
set(mindbot_msgs_URL_REPOSITORY "")
set(mindbot_msgs_DEPRECATED "")