rootProject.name = 'VisualSceneMaker'

include 'core'
include 'core-webserver'
include 'core-http-jdk'
include 'core-http-android'
include 'core-logic-jpl'
include 'editor'
include 'runtime-server'
include 'services'
include 'services:embeddings'
include 'services:semantic-analysis'
include 'services:semantic-ud'
include 'plugins:heartflow'
include 'plugins:alma'
include 'plugins:AndroidGui'
include 'plugins:charamel-ws'
include 'plugins:email'
include 'plugins:htmlgui-ws'
include 'plugins:user-cue-service'
include 'plugins:fortunecookie'
include 'plugins:ssj'
include 'plugins:qrwebcam'
include 'plugins:timer'
include 'plugins:unity'
include 'plugins:odp'
include 'plugins:studymaster-web'
include 'plugins:decad'
include 'plugins:wizard'
include 'plugins:yallah'
include 'plugins:ssi'
include 'plugins:reeti'
include 'plugins:tricatworld'
include 'plugins:charamel'
include 'plugins:DriveSimulator'
include 'plugins:sockets'
include 'plugins:voicetts'
include 'plugins:asr'
include 'plugins:llm'
findProject(':plugins:DriveSimulator')?.name = 'DriveSimulator'
