plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group 'de.dfki'
version '4.0.1'


repositories {
    mavenCentral()
}
javafx {
    version = '21'
    modules = [ 'javafx.controls', 'javafx.graphics', 'javafx.fxml', 'javafx.swing' ]
}
dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    implementation project(":core")
}
