// Generated by gencpp from file mindbot_msgs/SetCtrlStateRequest.msg
// DO NOT EDIT!


#ifndef MINDBOT_MSGS_MESSAGE_SETCTRLSTATEREQUEST_H
#define MINDBOT_MSGS_MESSAGE_SETCTRLSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mindbot_msgs/CtrlState.h>

namespace mindbot_msgs
{
template <class ContainerAllocator>
struct SetCtrlStateRequest_
{
  typedef SetCtrlStateRequest_<ContainerAllocator> Type;

  SetCtrlStateRequest_()
    : ctrl_state()  {
    }
  SetCtrlStateRequest_(const ContainerAllocator& _alloc)
    : ctrl_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mindbot_msgs::CtrlState_<ContainerAllocator>  _ctrl_state_type;
  _ctrl_state_type ctrl_state;





  typedef boost::shared_ptr< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCtrlStateRequest_

typedef ::mindbot_msgs::SetCtrlStateRequest_<std::allocator<void> > SetCtrlStateRequest;

typedef boost::shared_ptr< ::mindbot_msgs::SetCtrlStateRequest > SetCtrlStateRequestPtr;
typedef boost::shared_ptr< ::mindbot_msgs::SetCtrlStateRequest const> SetCtrlStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator1> & lhs, const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ctrl_state == rhs.ctrl_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator1> & lhs, const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mindbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c11e4fe52b5a04acc1f4850c19306fe";
  }

  static const char* value(const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c11e4fe52b5a04aULL;
  static const uint64_t static_value2 = 0xcc1f4850c19306feULL;
};

template<class ContainerAllocator>
struct DataType< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mindbot_msgs/SetCtrlStateRequest";
  }

  static const char* value(const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#SetCtrlState service\n"
"\n"
"#REQUEST\n"
"mindbot_msgs/CtrlState ctrl_state\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mindbot_msgs/CtrlState\n"
"#CtrlState message\n"
"\n"
"#List of the available control states\n"
"uint8 OFF = 0\n"
"uint8 ON = 1\n"
"uint8 ERROR = 2\n"
"\n"
"#Assigned control state\n"
"uint8 ctrl_state\n"
;
  }

  static const char* value(const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ctrl_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCtrlStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mindbot_msgs::SetCtrlStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "ctrl_state: ";
    s << std::endl;
    Printer< ::mindbot_msgs::CtrlState_<ContainerAllocator> >::stream(s, indent + "  ", v.ctrl_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINDBOT_MSGS_MESSAGE_SETCTRLSTATEREQUEST_H
