// Generated by gencpp from file mindbot_msgs/SetJointStateResponse.msg
// DO NOT EDIT!


#ifndef MINDBOT_MSGS_MESSAGE_SETJOINTSTATERESPONSE_H
#define MINDBOT_MSGS_MESSAGE_SETJOINTSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mindbot_msgs
{
template <class ContainerAllocator>
struct SetJointStateResponse_
{
  typedef SetJointStateResponse_<ContainerAllocator> Type;

  SetJointStateResponse_()
    : success(false)
    , message()  {
    }
  SetJointStateResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointStateResponse_

typedef ::mindbot_msgs::SetJointStateResponse_<std::allocator<void> > SetJointStateResponse;

typedef boost::shared_ptr< ::mindbot_msgs::SetJointStateResponse > SetJointStateResponsePtr;
typedef boost::shared_ptr< ::mindbot_msgs::SetJointStateResponse const> SetJointStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator1> & lhs, const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator1> & lhs, const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mindbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mindbot_msgs/SetJointStateResponse";
  }

  static const char* value(const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"#RESPONSE\n"
"bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mindbot_msgs::SetJointStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINDBOT_MSGS_MESSAGE_SETJOINTSTATERESPONSE_H
