
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 22 22:03:33 CEST 2015
//----------------------------------------------------

package de.dfki.vsm.sfsl.parser;

/** CUP generated interface containing symbol constants. */
public interface _SFSLToken_ {
  /* terminals */
  public static final int RANDOM = 18;
  public static final int EMPTY = 41;
  public static final int REMOVE = 9;
  public static final int INTEGER = 56;
  public static final int NOTEQUAL = 13;
  public static final int LPAREN = 26;
  public static final int GREATER = 15;
  public static final int HISTORYCONTAINSSTATE = 49;
  public static final int LESS = 14;
  public static final int MINUS = 5;
  public static final int REMOVEFIRST = 19;
  public static final int RPAREN = 27;
  public static final int NOT = 37;
  public static final int AND = 3;
  public static final int USG = 45;
  public static final int ADDLAST = 11;
  public static final int LESSEQUAL = 16;
  public static final int VALUEOF = 53;
  public static final int FIRST = 21;
  public static final int TIMEOUT = 42;
  public static final int IN = 40;
  public static final int OR = 2;
  public static final int HISTORYRUNTIMEOF = 52;
  public static final int COMMA = 32;
  public static final int GET = 8;
  public static final int EQUALEQUAL = 12;
  public static final int DIV = 7;
  public static final int PLUS = 4;
  public static final int HISTORYSETDEPTH = 51;
  public static final int DOT = 35;
  public static final int BOOLEAN = 58;
  public static final int EOF = 0;
  public static final int EQUAL = 38;
  public static final int SIZE = 24;
  public static final int NEW = 54;
  public static final int UASG = 46;
  public static final int error = 1;
  public static final int NULL = 60;
  public static final int CONTAINS = 25;
  public static final int LBRACK = 28;
  public static final int GREATEREQUAL = 17;
  public static final int TIMES = 6;
  public static final int ADDFIRST = 10;
  public static final int COLON = 34;
  public static final int LAST = 22;
  public static final int LBRACE = 30;
  public static final int VARIABLE = 55;
  public static final int HISTORYDEEPCLEAR = 48;
  public static final int HISTORYVALUEOF = 50;
  public static final int RBRACK = 29;
  public static final int DEFAULT = 39;
  public static final int FLOAT = 57;
  public static final int CLEAR = 23;
  public static final int RBRACE = 31;
  public static final int HISTORYCLEAR = 47;
  public static final int REMOVELAST = 20;
  public static final int STRING = 59;
  public static final int PDA = 44;
  public static final int QUESTION = 33;
  public static final int PSG = 43;
  public static final int AT = 36;
}

