
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 17 21:49:17 CET 2014
//----------------------------------------------------

package de.dfki.vsm.model.script;

/** CUP generated interface containing symbol constants. */
public interface ScriptFields {
  /* terminals */
  public static final int PUNCTUATION = 5;
  public static final int PLACEHOLDER = 8;
  public static final int UNDERLINE = 14;
  public static final int SIMPLEWORD = 2;
  public static final int IDENTIFIER = 17;
  public static final int ABBREVIATION = 3;
  public static final int LANGUAGE = 15;
  public static final int VARIABLE = 4;
  public static final int ACTIONFOOT = 7;
  public static final int BOOLEAN = 9;
  public static final int STRING = 12;
  public static final int SCENEHEADER = 21;
  public static final int EOF = 0;
  public static final int FLOATING = 11;
  public static final int COMMENT = 16;
  public static final int COLONMARK = 13;
  public static final int NEWLINE = 18;
  public static final int error = 1;
  public static final int ERRORSTATE = 22;
  public static final int ACTIONHEAD = 6;
  public static final int ASSIGNMENT = 20;
  public static final int INTEGER = 10;
  public static final int WHITESPACE = 19;
}

