plugins {
    id 'java'
}

group 'de.dfki.vsm'


if(!project.hasProperty('flavor')){
    apply plugin: 'java'
    version "android-4.0.1"

    println("Building jar for ANDROID")
}
compileJava{
   //options.release = 8
}
repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/libs-release" }
}

dependencies {
    compileOnly group: 'com.github.vbmacher', name: 'java-cup-runtime', version: '11b-20160615'
    runtimeOnly group: 'com.github.vbmacher', name: 'java-cup-runtime', version: '11b-20160615'
    // https://mvnrepository.com/artifact/jpl/jpl
    implementation group: 'jpl', name: 'jpl', version: '7.4.0'
    // https://mvnrepository.com/artifact/org.jetbrains/annotations
    implementation group: 'org.jetbrains', name: 'annotations', version: '17.0.0'
    // https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
    implementation group: 'javax.xml.bind', name: 'jaxb-api', version: '2.4.0-b180830.0359'
    // https://mvnrepository.com/artifact/io.javalin/javalin
    implementation group: 'io.javalin', name: 'javalin', version: '4.6.8'
    // https://mvnrepository.com/artifact/org.json/json
    implementation group: 'org.json', name: 'json', version: '20240303'

}

def webUiSourceDir = rootProject.file("editor/src/main/resources/web-ui")
def webUiTargetDir = file("src/main/resources/web-ui")

tasks.register("syncWebUi", Sync) {
    dependsOn project(":editor").tasks.named("webUiBuild")
    from(webUiSourceDir)
    into(webUiTargetDir)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    onlyIf { webUiSourceDir.exists() }
}

processResources.dependsOn tasks.named("syncWebUi")


jar {
    doFirst {
        project.ext.set('flavor', 'android')
        project.ext.set('buildInfo', 'android')
    }

    from {
        (configurations.runtimeClasspath).collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    manifest {
        attributes(
                'Main-Class': 'de.dfki.vsm.Core'

        )
    }
    duplicatesStrategy = 'exclude'
}
