plugins {
    id 'java'
}

group 'de.dfki'
version '1.0.0'



repositories {
    mavenCentral()
}

dependencies {

    implementation project(path: ':plugins:sockets')
    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    testRuntimeOnly group: 'org.junit.vintage', name: 'junit-vintage-engine', version: '5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
    implementation project(":core")
    implementation group: 'com.google.code.gson', name: 'gson', version: '2.11.0'
    implementation 'io.socket:socket.io-client:2.1.2'
    implementation 'com.squareup.okhttp3:okhttp:3.14.9'
    implementation 'com.squareup.okio:okio:1.17.6'
}

test {
    useJUnitPlatform()
}
