
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 15 15:54:36 CEST 2017
//----------------------------------------------------

package de.dfki.vsm.model.sceneflow.glue;

/** CUP generated interface containing symbol constants. */
public interface GlueFields {
  /* terminals */
  public static final int SHORT = 54;
  public static final int IDENTIFIER = 66;
  public static final int TIMES = 34;
  public static final int BOOL = 58;
  public static final int ARROW = 37;
  public static final int HistorySetDepth = 15;
  public static final int NOTMINUS = 21;
  public static final int InState = 6;
  public static final int RBRACK = 45;
  public static final int COMMA = 48;
  public static final int RBRACE = 47;
  public static final int RPAREN = 43;
  public static final int LBRACK = 44;
  public static final int ANDAND = 27;
  public static final int OROR = 28;
  public static final int PlayAction = 2;
  public static final int DOUBLE = 57;
  public static final int LBRACE = 46;
  public static final int LPAREN = 42;
  public static final int LNOT = 38;
  public static final int INTEGER_LITERAL = 69;
  public static final int NOT = 39;
  public static final int HistoryClearFlat = 11;
  public static final int OBJECT = 64;
  public static final int DEC = 41;
  public static final int VAR = 61;
  public static final int FLOAT = 56;
  public static final int UnblockSceneGroup = 9;
  public static final int Timeout = 17;
  public static final int MOD = 36;
  public static final int BOOLEAN_LITERAL = 70;
  public static final int CLASS = 63;
  public static final int LESSEQUAL = 25;
  public static final int LONG = 55;
  public static final int PLUS = 32;
  public static final int QUESTION = 50;
  public static final int GREATEREQUAL = 26;
  public static final int EQUAL = 52;
  public static final int CHAR = 59;
  public static final int UnblockSceneScript = 10;
  public static final int GREATER = 24;
  public static final int HistoryValueOf = 14;
  public static final int DIV = 35;
  public static final int Contains = 8;
  public static final int FUN = 62;
  public static final int DOT = 49;
  public static final int INT = 53;
  public static final int Random = 7;
  public static final int STRING_LITERAL = 68;
  public static final int EOF = 0;
  public static final int NOTTILDE = 65;
  public static final int StopAction = 3;
  public static final int INC = 40;
  public static final int OBJECT_LITERAL = 71;
  public static final int MINUS = 33;
  public static final int PlayDialogAct = 4;
  public static final int FLOAT_LITERAL = 67;
  public static final int OR = 30;
  public static final int error = 1;
  public static final int QSTMINUS = 22;
  public static final int PlayScene = 5;
  public static final int COLON = 51;
  public static final int HistoryClearDeep = 12;
  public static final int HistoryRunTimeOf = 16;
  public static final int NOTEQUAL = 20;
  public static final int HistoryContains = 13;
  public static final int EQUALEQUAL = 19;
  public static final int NEW = 18;
  public static final int STRING = 60;
  public static final int LESS = 23;
  public static final int AND = 29;
  public static final int XOR = 31;
}

