
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 07 14:28:31 CET 2018
//----------------------------------------------------

package de.dfki.vsm.model.sceneflow.glue;

/** CUP generated interface containing symbol constants. */
public interface GlueFields {
  /* terminals */
  public static final int SHORT = 58;
  public static final int IDENTIFIER = 68;
  public static final int TIMES = 38;
  public static final int BOOL = 62;
  public static final int ARROW = 41;
  public static final int HistorySetDepth = 15;
  public static final int NOTMINUS = 25;
  public static final int InState = 6;
  public static final int RBRACK = 49;
  public static final int COMMA = 52;
  public static final int RBRACE = 51;
  public static final int RPAREN = 47;
  public static final int LBRACK = 48;
  public static final int ANDAND = 31;
  public static final int Fun = 20;
  public static final int OROR = 32;
  public static final int PlayAction = 2;
  public static final int DOUBLE = 61;
  public static final int LBRACE = 50;
  public static final int LPAREN = 46;
  public static final int LNOT = 42;
  public static final int INTEGER_LITERAL = 71;
  public static final int NOT = 43;
  public static final int HistoryClearFlat = 11;
  public static final int OBJECT = 66;
  public static final int DEC = 45;
  public static final int VAR = 65;
  public static final int FLOAT = 60;
  public static final int UnblockSceneGroup = 9;
  public static final int Timeout = 17;
  public static final int BOOLEAN_LITERAL = 72;
  public static final int MOD = 40;
  public static final int List = 18;
  public static final int LESSEQUAL = 29;
  public static final int LONG = 59;
  public static final int PLUS = 36;
  public static final int QUESTION = 54;
  public static final int GREATEREQUAL = 30;
  public static final int EQUAL = 56;
  public static final int CHAR = 63;
  public static final int UnblockSceneScript = 10;
  public static final int GREATER = 28;
  public static final int HistoryValueOf = 14;
  public static final int DIV = 39;
  public static final int Contains = 8;
  public static final int DOT = 53;
  public static final int INT = 57;
  public static final int Random = 7;
  public static final int STRING_LITERAL = 70;
  public static final int EOF = 0;
  public static final int NOTTILDE = 67;
  public static final int StopAction = 3;
  public static final int Struct = 19;
  public static final int INC = 44;
  public static final int OBJECT_LITERAL = 73;
  public static final int MINUS = 37;
  public static final int PlayDialogAct = 4;
  public static final int FLOAT_LITERAL = 69;
  public static final int OR = 34;
  public static final int error = 1;
  public static final int QSTMINUS = 26;
  public static final int PlayScene = 5;
  public static final int COLON = 55;
  public static final int HistoryClearDeep = 12;
  public static final int HistoryRunTimeOf = 16;
  public static final int NOTEQUAL = 24;
  public static final int HistoryContains = 13;
  public static final int EQUALEQUAL = 23;
  public static final int Class = 21;
  public static final int NEW = 22;
  public static final int STRING = 64;
  public static final int LESS = 27;
  public static final int AND = 33;
  public static final int XOR = 35;
}

