plugins {
    id 'java'
}

group 'de.dfki.vsm'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'io.javalin', name: 'javalin', version: '6.7.0'
    implementation group: 'org.json', name: 'json', version: '20240303'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
