set(_CATKIN_CURRENT_PACKAGE "communication_package")
set(communication_package_VERSION "0.1.0")
set(communication_package_MAINTAINER "sarah <sarah@todo.todo>")
set(communication_package_PACKAGE_FORMAT "2")
set(communication_package_BUILD_DEPENDS "rosjava_build_tools" "message_generation" "mindbot_msgs")
set(communication_package_BUILD_EXPORT_DEPENDS )
set(communication_package_BUILDTOOL_DEPENDS "catkin")
set(communication_package_BUILDTOOL_EXPORT_DEPENDS )
set(communication_package_EXEC_DEPENDS "mindbot_msgs" "message_runtime")
set(communication_package_RUN_DEPENDS "mindbot_msgs" "message_runtime")
set(communication_package_TEST_DEPENDS )
set(communication_package_DOC_DEPENDS )
set(communication_package_URL_WEBSITE "")
set(communication_package_URL_BUGTRACKER "")
set(communication_package_URL_REPOSITORY "")
set(communication_package_DEPRECATED "")