// Generated by gencpp from file mindbot_msgs/SetCtrlMode.msg
// DO NOT EDIT!


#ifndef MINDBOT_MSGS_MESSAGE_SETCTRLMODE_H
#define MINDBOT_MSGS_MESSAGE_SETCTRLMODE_H

#include <ros/service_traits.h>


#include <mindbot_msgs/SetCtrlModeRequest.h>
#include <mindbot_msgs/SetCtrlModeResponse.h>


namespace mindbot_msgs
{

struct SetCtrlMode
{

typedef SetCtrlModeRequest Request;
typedef SetCtrlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCtrlMode
} // namespace mindbot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mindbot_msgs::SetCtrlMode > {
  static const char* value()
  {
    return "f628f1e6fadee58433a3f4d581cef831";
  }

  static const char* value(const ::mindbot_msgs::SetCtrlMode&) { return value(); }
};

template<>
struct DataType< ::mindbot_msgs::SetCtrlMode > {
  static const char* value()
  {
    return "mindbot_msgs/SetCtrlMode";
  }

  static const char* value(const ::mindbot_msgs::SetCtrlMode&) { return value(); }
};


// service_traits::MD5Sum< ::mindbot_msgs::SetCtrlModeRequest> should match
// service_traits::MD5Sum< ::mindbot_msgs::SetCtrlMode >
template<>
struct MD5Sum< ::mindbot_msgs::SetCtrlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mindbot_msgs::SetCtrlMode >::value();
  }
  static const char* value(const ::mindbot_msgs::SetCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mindbot_msgs::SetCtrlModeRequest> should match
// service_traits::DataType< ::mindbot_msgs::SetCtrlMode >
template<>
struct DataType< ::mindbot_msgs::SetCtrlModeRequest>
{
  static const char* value()
  {
    return DataType< ::mindbot_msgs::SetCtrlMode >::value();
  }
  static const char* value(const ::mindbot_msgs::SetCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mindbot_msgs::SetCtrlModeResponse> should match
// service_traits::MD5Sum< ::mindbot_msgs::SetCtrlMode >
template<>
struct MD5Sum< ::mindbot_msgs::SetCtrlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mindbot_msgs::SetCtrlMode >::value();
  }
  static const char* value(const ::mindbot_msgs::SetCtrlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mindbot_msgs::SetCtrlModeResponse> should match
// service_traits::DataType< ::mindbot_msgs::SetCtrlMode >
template<>
struct DataType< ::mindbot_msgs::SetCtrlModeResponse>
{
  static const char* value()
  {
    return DataType< ::mindbot_msgs::SetCtrlMode >::value();
  }
  static const char* value(const ::mindbot_msgs::SetCtrlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINDBOT_MSGS_MESSAGE_SETCTRLMODE_H
