// Generated by gencpp from file mindbot_msgs/SetCtrlModeRequest.msg
// DO NOT EDIT!


#ifndef MINDBOT_MSGS_MESSAGE_SETCTRLMODEREQUEST_H
#define MINDBOT_MSGS_MESSAGE_SETCTRLMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mindbot_msgs/CtrlMode.h>

namespace mindbot_msgs
{
template <class ContainerAllocator>
struct SetCtrlModeRequest_
{
  typedef SetCtrlModeRequest_<ContainerAllocator> Type;

  SetCtrlModeRequest_()
    : ctrl_mode()  {
    }
  SetCtrlModeRequest_(const ContainerAllocator& _alloc)
    : ctrl_mode(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mindbot_msgs::CtrlMode_<ContainerAllocator>  _ctrl_mode_type;
  _ctrl_mode_type ctrl_mode;





  typedef boost::shared_ptr< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCtrlModeRequest_

typedef ::mindbot_msgs::SetCtrlModeRequest_<std::allocator<void> > SetCtrlModeRequest;

typedef boost::shared_ptr< ::mindbot_msgs::SetCtrlModeRequest > SetCtrlModeRequestPtr;
typedef boost::shared_ptr< ::mindbot_msgs::SetCtrlModeRequest const> SetCtrlModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator1> & lhs, const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ctrl_mode == rhs.ctrl_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator1> & lhs, const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mindbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45573c06451852ab4829ec27b7af4563";
  }

  static const char* value(const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45573c06451852abULL;
  static const uint64_t static_value2 = 0x4829ec27b7af4563ULL;
};

template<class ContainerAllocator>
struct DataType< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mindbot_msgs/SetCtrlModeRequest";
  }

  static const char* value(const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#SetCtrlMode service\n"
"\n"
"#REQUEST\n"
"mindbot_msgs/CtrlMode ctrl_mode\n"
"\n"
"\n"
"================================================================================\n"
"MSG: mindbot_msgs/CtrlMode\n"
"#CtrlMode message\n"
"\n"
"#List of the available control modes\n"
"uint8 MODE0 = 0\n"
"uint8 MODE1 = 1\n"
"uint8 MODE2 = 2\n"
"\n"
"#Assigned control mode\n"
"uint8 ctrl_mode\n"
;
  }

  static const char* value(const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ctrl_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCtrlModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mindbot_msgs::SetCtrlModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "ctrl_mode: ";
    s << std::endl;
    Printer< ::mindbot_msgs::CtrlMode_<ContainerAllocator> >::stream(s, indent + "  ", v.ctrl_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINDBOT_MSGS_MESSAGE_SETCTRLMODEREQUEST_H
