// Generated by gencpp from file mindbot_msgs/SetPose.msg
// DO NOT EDIT!


#ifndef MINDBOT_MSGS_MESSAGE_SETPOSE_H
#define MINDBOT_MSGS_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <mindbot_msgs/SetPoseRequest.h>
#include <mindbot_msgs/SetPoseResponse.h>


namespace mindbot_msgs
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace mindbot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mindbot_msgs::SetPose > {
  static const char* value()
  {
    return "28e4dd667b29bd35b516ba1d379b7529";
  }

  static const char* value(const ::mindbot_msgs::SetPose&) { return value(); }
};

template<>
struct DataType< ::mindbot_msgs::SetPose > {
  static const char* value()
  {
    return "mindbot_msgs/SetPose";
  }

  static const char* value(const ::mindbot_msgs::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::mindbot_msgs::SetPoseRequest> should match
// service_traits::MD5Sum< ::mindbot_msgs::SetPose >
template<>
struct MD5Sum< ::mindbot_msgs::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mindbot_msgs::SetPose >::value();
  }
  static const char* value(const ::mindbot_msgs::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mindbot_msgs::SetPoseRequest> should match
// service_traits::DataType< ::mindbot_msgs::SetPose >
template<>
struct DataType< ::mindbot_msgs::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::mindbot_msgs::SetPose >::value();
  }
  static const char* value(const ::mindbot_msgs::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mindbot_msgs::SetPoseResponse> should match
// service_traits::MD5Sum< ::mindbot_msgs::SetPose >
template<>
struct MD5Sum< ::mindbot_msgs::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mindbot_msgs::SetPose >::value();
  }
  static const char* value(const ::mindbot_msgs::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mindbot_msgs::SetPoseResponse> should match
// service_traits::DataType< ::mindbot_msgs::SetPose >
template<>
struct DataType< ::mindbot_msgs::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::mindbot_msgs::SetPose >::value();
  }
  static const char* value(const ::mindbot_msgs::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINDBOT_MSGS_MESSAGE_SETPOSE_H
