// Generated by gencpp from file mindbot_msgs/SetVector3.msg
// DO NOT EDIT!


#ifndef MINDBOT_MSGS_MESSAGE_SETVECTOR3_H
#define MINDBOT_MSGS_MESSAGE_SETVECTOR3_H

#include <ros/service_traits.h>


#include <mindbot_msgs/SetVector3Request.h>
#include <mindbot_msgs/SetVector3Response.h>


namespace mindbot_msgs
{

struct SetVector3
{

typedef SetVector3Request Request;
typedef SetVector3Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetVector3
} // namespace mindbot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mindbot_msgs::SetVector3 > {
  static const char* value()
  {
    return "efb349b09ac9e0d4c8ef08d9ad9508b4";
  }

  static const char* value(const ::mindbot_msgs::SetVector3&) { return value(); }
};

template<>
struct DataType< ::mindbot_msgs::SetVector3 > {
  static const char* value()
  {
    return "mindbot_msgs/SetVector3";
  }

  static const char* value(const ::mindbot_msgs::SetVector3&) { return value(); }
};


// service_traits::MD5Sum< ::mindbot_msgs::SetVector3Request> should match
// service_traits::MD5Sum< ::mindbot_msgs::SetVector3 >
template<>
struct MD5Sum< ::mindbot_msgs::SetVector3Request>
{
  static const char* value()
  {
    return MD5Sum< ::mindbot_msgs::SetVector3 >::value();
  }
  static const char* value(const ::mindbot_msgs::SetVector3Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::mindbot_msgs::SetVector3Request> should match
// service_traits::DataType< ::mindbot_msgs::SetVector3 >
template<>
struct DataType< ::mindbot_msgs::SetVector3Request>
{
  static const char* value()
  {
    return DataType< ::mindbot_msgs::SetVector3 >::value();
  }
  static const char* value(const ::mindbot_msgs::SetVector3Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mindbot_msgs::SetVector3Response> should match
// service_traits::MD5Sum< ::mindbot_msgs::SetVector3 >
template<>
struct MD5Sum< ::mindbot_msgs::SetVector3Response>
{
  static const char* value()
  {
    return MD5Sum< ::mindbot_msgs::SetVector3 >::value();
  }
  static const char* value(const ::mindbot_msgs::SetVector3Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::mindbot_msgs::SetVector3Response> should match
// service_traits::DataType< ::mindbot_msgs::SetVector3 >
template<>
struct DataType< ::mindbot_msgs::SetVector3Response>
{
  static const char* value()
  {
    return DataType< ::mindbot_msgs::SetVector3 >::value();
  }
  static const char* value(const ::mindbot_msgs::SetVector3Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINDBOT_MSGS_MESSAGE_SETVECTOR3_H
