// Generated by gencpp from file mindbot_msgs/SetVector3Request.msg
// DO NOT EDIT!


#ifndef MINDBOT_MSGS_MESSAGE_SETVECTOR3REQUEST_H
#define MINDBOT_MSGS_MESSAGE_SETVECTOR3REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace mindbot_msgs
{
template <class ContainerAllocator>
struct SetVector3Request_
{
  typedef SetVector3Request_<ContainerAllocator> Type;

  SetVector3Request_()
    : data()  {
    }
  SetVector3Request_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetVector3Request_

typedef ::mindbot_msgs::SetVector3Request_<std::allocator<void> > SetVector3Request;

typedef boost::shared_ptr< ::mindbot_msgs::SetVector3Request > SetVector3RequestPtr;
typedef boost::shared_ptr< ::mindbot_msgs::SetVector3Request const> SetVector3RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mindbot_msgs::SetVector3Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mindbot_msgs::SetVector3Request_<ContainerAllocator1> & lhs, const ::mindbot_msgs::SetVector3Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mindbot_msgs::SetVector3Request_<ContainerAllocator1> & lhs, const ::mindbot_msgs::SetVector3Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mindbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "390cbff96d168abc35f84f5ed0728288";
  }

  static const char* value(const ::mindbot_msgs::SetVector3Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x390cbff96d168abcULL;
  static const uint64_t static_value2 = 0x35f84f5ed0728288ULL;
};

template<class ContainerAllocator>
struct DataType< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mindbot_msgs/SetVector3Request";
  }

  static const char* value(const ::mindbot_msgs::SetVector3Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#SetVector3 service\n"
"\n"
"#REQUEST\n"
"geometry_msgs/Vector3 data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mindbot_msgs::SetVector3Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetVector3Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mindbot_msgs::SetVector3Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mindbot_msgs::SetVector3Request_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINDBOT_MSGS_MESSAGE_SETVECTOR3REQUEST_H
